### ISSUE TITLE
Sound file does not load in CCL

### ISSUE THREAD

**Issue by nailuj24** [borodust/hello-gamekit#2]
Hi,
first of all, your engine looks really cool! But I've encountered a problem following your [Getting Started](https://borodust.org/projects/trivial-gamekit/getting-started/) guide.
Everything seems to work well, up to the point where I try to load the .ogg file with
```clojure
(gamekit:define-sound :snake-grab "snake-grab.ogg")
```
ccl gives me
```
> Error: Undefined function WIN64::|memcpy| called with arguments (#<A Foreign Pointer #x751560> #<A Foreign Pointer #x746588> 12) .
> While executing: SNDFILE::REPLACE-FOREIGN-MEMORY, in process listener(1).
``` 
Here's the full backtrace:
```
*(22C59398) : 0 (REPLACE-FOREIGN-MEMORY #<A Foreign Pointer #x224C6588> #<A Foreign Pointer #x224D0580> 12) 85
 (22C59418) : 1 (FUNCALL #'#<(:INTERNAL CFFI-CALLBACKS::|SNDFILE::VIO-READ|)> #<A Foreign Pointer #x224D0580> 12 #<A Null Foreign Pointer>) 93
 (22C59448) : 2 (FUNCALL #'#<CFFI-CALLBACKS::|SNDFILE::VIO-READ|> 72646524) 589
 (22C59480) : 3 (%PASCAL-FUNCTIONS% 13 72646524) 365
 (22C59538) : 4 (OPEN-VIRTUAL #<VIRTUAL-IO {#X224D6190}> 16 #<INFO {#X224D6280}> #<A Null Foreign Pointer>) 1669
 (22C59590) : 5 (FUNCALL #'#<(:INTERNAL #:OPEN-FILE56812 (CL-BODGE.RESOURCES:DECODE-RESOURCE (CL-BODGE.RESOURCES::AUDIO-RESOURCE-HANDLER T)))> #<INFO {#X224D6280}>) 109
 (22C595B8) : 6 (FUNCALL #'#<#<STANDARD-METHOD CL-BODGE.RESOURCES:DECODE-RESOURCE (CL-BODGE.RESOURCES::AUDIO-RESOURCE-HANDLER T)>> #<CL-BODGE.RESOURCES::AUDIO-RESOURCE-HANDLER #x2102DD897D> #<BASIC-FILE-BINARY-INPUT-STREAM ("C:/Users/julia/Desktop/gamekit/snake-grab.ogg"/10032 ISO-8859-1) #x2102DD744D>) 365
 (22C59668) : 7 (LOAD-RESOURCE #P"/_asset/KEYWORD/SNAKE-GRAB") 853
 (22C596D8) : 8 (INVOKE-WITH-RESTARTS #<COMPILED-LEXICAL-CLOSURE (:INTERNAL #:BODY-FU55572 CL-BODGE.RESOURCES:RESOURCE-FLOW) #x2102DD769F> NIL) 429
 (22C59730) : 9 (FUNCALL #'#<(:INTERNAL CL-FLOW::DISPATCHED CL-FLOW::INVOKE-ATOMICALLY)>) 229
 (22C59788) : 10 (FUNCALL #'#<(:INTERNAL CL-BODGE.ENGINE::TRAPS-MASKING-TASK (CL-BODGE.CONCURRENCY:DISPATCH (CL-BODGE.ENGINE::BODGE-ENGINE FUNCTION T)))>) 293
 (22C597E0) : 11 (FUNCALL #'#<#<STANDARD-METHOD CL-BODGE.CONCURRENCY:DISPATCH (CL-BODGE.ENGINE::BODGE-ENGINE FUNCTION T)>> #<CL-BODGE.ENGINE::BODGE-ENGINE #x2102D5940D> #<COMPILED-LEXICAL-CLOSURE (:INTERNAL CL-FLOW::DISPATCHED CL-FLOW::INVOKE-ATOMICALLY) #x2102DD75FF> NIL) 677
 (22C59860) : 12 (FUNCALL #'#<CL-BODGE.ENGINE::%DISPATCH> #<COMPILED-LEXICAL-CLOSURE (:INTERNAL CL-FLOW::DISPATCHED CL-FLOW::INVOKE-ATOMICALLY) #x2102DD75FF> NIL) 213
 (22C59890) : 13 (FUNCALL #'#<(:INTERNAL CL-FLOW::RESOLVE CL-FLOW::DISPATCH-PARALLEL-FLOW)> (#<COMPILED-LEXICAL-CLOSURE # #x2102DD7E1F>)) 341
 (22C598E0) : 14 (FUNCALL #'#<(:INTERNAL CL-FLOW::RESOLVE CL-FLOW::DISPATCH-PARALLEL-FLOW)> ((#))) 285
 (22C59930) : 15 (FUNCALL #'#<(:INTERNAL CL-FLOW::RESOLVE CL-FLOW::DISPATCH-PARALLEL-FLOW)> (#<COMPILED-LEXICAL-CLOSURE # #x2102DD7C5F>)) 341
 (22C59980) : 16 (FUNCALL #'#<(:INTERNAL CL-FLOW::RESOLVE CL-FLOW::DISPATCH-PARALLEL-FLOW)> ((#))) 285
 (22C599D0) : 17 (FUNCALL #'#<CL-BODGE.ENGINE:RUN> #<COMPILED-LEXICAL-CLOSURE (:INTERNAL TRIVIAL-GAMEKIT:PREPARE-RESOURCES) #x2102DD7AAF>) 213
 (22C599F8) : 18 (PREPARE-RESOURCES :SNAKE-GRAB) 1229
 (22C59A38) : 19 (AUTOPREPARE :SNAKE-GRAB) 117
 (22C59A58) : 20 (FUNCALL #'#<Anonymous Function #x2102DD89AF>) 101
 (22C59A70) : 21 (TOPLEVEL-EVAL (TRIVIAL-GAMEKIT:DEFINE-SOUND :SNAKE-GRAB "snake-grab.ogg") NIL) 693
 (22C59B00) : 22 (READ-LOOP :INPUT-STREAM #<SYNONYM-STREAM to *TERMINAL-IO* #x210041949D> :OUTPUT-STREAM #<SYNONYM-STREAM to *TERMINAL-IO* #x210041933D> :BREAK-LEVEL 0 :PROMPT-FUNCTION #<Compiled-function (:INTERNAL CCL::READ-LOOP) (Non-Global)  #x10053660F>) 2269
 (22C59D58) : 23 (RUN-READ-LOOP :BREAK-LEVEL 0) 157
 (22C59D80) : 24 (TOPLEVEL-LOOP) 101
 (22C59DA8) : 25 (FUNCALL #'#<(:INTERNAL (TOPLEVEL-FUNCTION (CCL::LISP-DEVELOPMENT-SYSTEM T)))>) 101
 (22C59DC8) : 26 (FUNCALL #'#<(:INTERNAL CCL::MAKE-MCL-LISTENER-PROCESS)>) 661
 (22C59E60) : 27 (RUN-PROCESS-INITIAL-FORM #<TTY-LISTENER listener(1) [Active] #x210041818D> (#<COMPILED-LEXICAL-CLOSURE # #x2100417CBF>)) 669
 (22C59EF0) : 28 (FUNCALL #'#<(:INTERNAL (CCL::%PROCESS-PRESET-INTERNAL (PROCESS)))> #<TTY-LISTENER listener(1) [Active] #x210041818D> (#<COMPILED-LEXICAL-CLOSURE # #x2100417CBF>)) 573
 (22C59F98) : 29 (FUNCALL #'#<(:INTERNAL CCL::THREAD-MAKE-STARTUP-FUNCTION)>) 277
```
To my unschooled eye it looks like something in cl-flow is preventing macro expansion for `#_memcpy` in the [static-vectors](https://github.com/sionescu/static-vectors/blob/master/src/impl-clozure.lisp#L15) lib, expecting it to be a function (`#_memcpy` is bound to the `WIN64::|memcpy|` macro I think).
This reproduces every time, so I can provide additional info if you need it.
I'm using the 64 bit version of `ccl 1.11.5` on `Windows 10 64 bit`

**Comment by borodust** [comment]
Thank you for the report! This oftentimes happens with manually built CCL. People had similar issues (https://github.com/borodust/notalone/issues/3), but only thing I could suggest is to ask CCL maintainers what could went wrong with a particular installation.

I could't reproduce the issue last time it was reported, but I would try to do that again today when I get to my dev machine. Maybe a different issue this time.

**Comment by borodust** [comment]
Yes, unfortunately, I couldn't reproduce this issue with latest [CCL](https://github.com/Clozure/ccl/releases/download/v1.11.5/ccl-1.11.5-windowsx86.zip) on my Win10 64-bit machine.

You can seek help from CCL users in [#ccl](https://webchat.freenode.net/?channels=ccl) `freenode.net` channel while using [SBCL](http://prdownloads.sourceforge.net/sbcl/sbcl-1.4.2-x86-64-windows-binary.msi) in the meantime.

**Comment by nailuj24** [comment]
Alright, thanks for looking into it! It does work with SBCL without problems. I'll report back if I ever find out what caused the problem with CCL.

**Comment by nailuj24** [comment]
Okay, I found a way to fix this, but I don't fully understand why it works. I've made a modification to impl-clozure.lisp of the static-vectors package, wrapping the call to `#_memcpy` in a function, and indeed everything works now.
```clojure
; my custom wrapper
(declaim (inline replace-foreign-memory))
(defun mymemcpy (dst-ptr src-ptr length)
   (#_memcpy dst-ptr src-ptr length))

; original implementation, #_memcpy replaced with mymemcpy
(declaim (inline replace-foreign-memory))
(defun replace-foreign-memory (dst-ptr src-ptr length)
  "Copy LENGTH octets from foreign memory area SRC-PTR to DST-PTR."
  (mymemcpy dst-ptr src-ptr length)
  dst-ptr)
```

**Comment by borodust** [comment]
This is super weird. But if true, this is certainly a `#ccl` issue. Thanks a lot for looking into it!

**Comment by informatimago** [comment]
Indeed, some POSIX API are allowed to be C macros.  The actual function name may be different, which is a problem for FFI.
Hence the existance of libraries such as libfixposix.
So the right patch would be to add a lfp_memcpy to https://github.com/sionescu/libfixposix/blob/master/src/lib/string.c
and to use this library.
(or deal with it, as you did, but _memcpy is not standard, can vary from system to system or from version to version. It could be MemoryCopy or something else…)

cf. http://pubs.opengroup.org/onlinepubs/9699919799/functions/V2_chap02.html#tag_15_01 
"2. Any function declared in a header may also be implemented as a macro defined in the header, so a function should not be declared explicitly if its header is included. Any macro definition of a function can be suppressed locally by enclosing the name of the function in parentheses, because the name is then not followed by the <left-parenthesis> that indicates expansion of a macro function name. For the same syntactic reason, it is permitted to take the address of a function even if it is also defined as a macro. The use of the C-language #undef construct to remove any such macro definition shall also ensure that an actual function is referred to."
However the rest of that section seems to say that a function with the same name should exist anyway (since we can take &memcpy), so I don't know what's wrong here...

**Comment by borodust** [comment]
Looks like I have fixed the issue (ultimately, replacing the offending function with [another](https://github.com/borodust/bodge-sndfile/commit/e57475a5c1fb5674450aa72803b718dc76f68e78) one). Please, update bodge dist and try again (instructions below):
```lisp
(ql:update-all-dists)
(ql:quickload :hello-gamekit)
(gamekit:start 'hello-gamekit:hello-gamekit)
```

**Comment by nailuj24** [comment]
> Indeed, some POSIX API are allowed to be C macros. The actual function name may be different, which is a problem for FFI.

Nice find! I can confirm it works now with the latest bodge update.

**Comment by borodust** [comment]
Good! It's not actually related to POSIX/macro issue, but I'm glad it works now. Thanks!
